INSERT INTO famous_quotes (author, added_by, quote_type, quote_src, quote_tx) VALUES
('Michael Scott', 'bjarvis', 'fame', 'the-office', 'If I had a gun with two bullets and I was in a room with Hitler, Bin Laden, and Toby, I would shoot Toby twice.'),
('Michael Scott', 'bjarvis', 'fame', 'the-office', 'Occasionally, I’ll hit somebody with my car. So sue me.'),
('Michael Scott', 'bjarvis', 'fame', 'the-office', 'Everybody stay calm! Stay f*&#!#% calm!'),
('Michael Scott', 'bjarvis', 'fame', 'the-office', 'I. Declare. Bankruptcy!'),
('Michael Scott', 'bjarvis', 'fame', 'the-office', 'And I knew exactly what to do. But in a much more real sense, I had no idea what to do.'),
('Michael Scott', 'bjarvis', 'fame', 'the-office', 'I feel like all my kids grew up, and then they married each other. It’s every parent’s dream.'),
('Michael Scott', 'bjarvis', 'fame', 'the-office', 'Dwight, you ignorant slut!'),
('Michael Scott', 'bjarvis', 'fame', 'the-office', 'Well, Happy Birthday Jesus. Sorry your party’s so lame.'),
('Michael Scott', 'bjarvis', 'fame', 'the-office', 'Sometimes I’ll start a sentence, and I don’t even know where it’s going. I just hope I find it along the way.'),
('Michael Scott', 'bjarvis', 'fame', 'the-office', 'There are certain things a boss does not share with his employees. His salary, that would depress them. His bed, it--- And I am not going to tell them that I''ll be reading their e-mails.'),
('Pam Beesly', 'bjarvis', 'fame', 'the-office', 'Once every hour, someone is involved in an internet scam. That man is Michael Scott.'),
('Pam Beesly', 'bjarvis', 'fame', 'the-office', 'It''s performance review day, company-wide. Last year, my performance review started with Michael asking me what my hopes and dreams were, and it ended with him telling me he could bench-press 190 pounds. So, I don''t really know what to expect.'),
('Pam Beesly', 'bjarvis', 'fame', 'the-office', 'I feel God in this Chili’s tonight.'),
('Pam Beesly', 'bjarvis', 'fame', 'the-office', 'There’s a lot of beauty in ordinary things. Isn’t that kind of the point?'),
('Creed Bratton', 'bjarvis', 'fame', 'the-office', 'Two eyes. Two ears. A chin. A mouth. Ten fingers. Two nipples. A butt, two kneecaps, a penis. I''ve just described to you the Loch Ness monster. And the reward for his capture? All the riches in Scotland. So I have one question: Why are you here?'),
('Kevin Malone', 'bjarvis', 'fame', 'the-office', 'I am immensely proud of what I did for that turtle!'),
('Stanley Hudson', 'bjarvis', 'fame', 'the-office', 'I wake up every morning in a bed that''s too small, drive my daughter to a school that''s too expensive, and then I go to work to a job for which I get paid too little. But on pretzel day? Well, I like pretzel day.'),
('Stanley Hudson', 'bjarvis', 'fame', 'the-office', 'Did I stutter?'),
('Ryan Howard', 'bjarvis', 'fame', 'the-office', 'Last year, Creed asked me how to set up a blog. Wanting to protect the world from being exposed to Creed''s brain, I opened up a Word document on his computer and put an address at the top. I''ve read some of it. Even for the Internet, it''s... pretty shocking.'),
('Kelly Kapoor', 'bjarvis', 'fame', 'the-office', 'I don''t talk trash, I talk smack. They''re totally different. Trash talk is hypothetical, like: Your mom is so fat she can eat the internet. But smack talk is happening like right now. Like: You''re ugly and I know it for a fact ''cause I got the evidence right there.'),
('Kelly Kapoor', 'bjarvis', 'fame', 'the-office', 'I have a lot of questions. Number one, how dare you?'),
('Jim Halpert', 'bjarvis', 'fame', 'the-office', 'I had feelings today for a coworker that I haven''t had in years... In my defense he was grabbing my crotch fairly aggressively at the time.'),
('Jim Halpert', 'bjarvis', 'fame', 'the-office', 'Bears, Beets, Battlestar Galactica.'),
('Jim Halpert', 'bjarvis', 'fame', 'the-office', 'It''s true. I''m having a party. I''ve got three cases of imported beer, a karaoke machine, and I didn''t invite Michael. So three ingredients for a great party. And it''s nothing personal, I just think that if he were there, people wouldn''t be able to relax, and you know, have fun, and my roommate wants to meet everybody. Because I''m pretty sure he thinks that I''m making Dwight up. [sighs] He is very real.'),
('Andy Bernard', 'bjarvis', 'fame', 'the-office', 'I wish there was a way to know you’re in the good old days, before you’ve actually left them.'),
('Andy Bernard', 'bjarvis', 'fame', 'the-office', 'You can''t let a girl feel good about herself. It will backfire on you. Every compliment has to be backhanded. ''Oh I like your dress, but I''d like it more if you had prettier hair.'''),
('Andy Bernard', 'bjarvis', 'fame', 'the-office', 'I''ll be the Number Two guy here in Scranton in six weeks. How? Name repetition, personality mirroring, and never breaking off a handshake. I''m always thinking one step ahead. Like a carpenter that makes stairs.'),
('Andy Bernard', 'bjarvis', 'fame', 'the-office', 'Sorry I annoyed you with my friendship.'),
('Dwight Schrute', 'bjarvis', 'fame', 'the-office', 'Whenever I''m about to do something, I think, ''Would an idiot do that?'' And if they would, I do not do that thing.'),
('Dwight Schrute', 'bjarvis', 'fame', 'the-office', 'It has to be official, and it has to be urine.'),
('Dwight Schrute', 'bjarvis', 'fame', 'the-office', 'I have been Michael''s #2 guy for about 5 years. And we make a great team. We''re like one of those classic famous teams. He''s like Mozart, and I''m like Mozart''s friend. No. I''m like Butch Cassidy, and Michael is like Mozart. You try and hurt Mozart; you''re going to get a bullet in your head courtesy of Butch Cassidy.'),
('Dwight Schrute', 'bjarvis', 'fame', 'the-office', 'I.D. badges are long overdue. Security in this office park is a joke. Last year, I came to work with my spud gun in a duffel bag. I sat at my desk all day, with a rifle that shoots potatoes at 60 pounds per square inch. Can you imagine if I was deranged?'),
('Angela Martin', 'bjarvis', 'fame', 'the-office', 'If you pray enough, you can change yourself into a cat person.'),
('Angela Martin', 'bjarvis', 'fame', 'the-office', 'I know that patience and loyalty are good, and virtuous traits. But sometimes I just think you need to grow a pair.'),
('Oscar Martinez', 'bjarvis', 'fame', 'the-office', 'I didn''t realize how many of Angela''s opinions I agreed with...until she tried to have my knee caps shattered for sleeping with her husband.'),
('Phyllis Lapin', 'bjarvis', 'fame', 'the-office', 'I''m glad Michael''s getting help. He has a lot of issues, and he''s stupid.'),
('Toby Flenderson', 'bjarvis', 'fame', 'the-office', 'Chad Flenderman. Just an easy-going black guy who knows the streets--yet he also went to Oxford. So. Just as comfortable on a motorcycle as he is on Air Force One. Oh and he''s also the world''s leading Egyptologist.'),
('Erin Hannon', 'bjarvis', 'fame', 'the-office', 'Disposable cameras are fun, but it seems a little wasteful. You never get to see your pictures. If it''s an important event that you want to remember, I recommend using a real camera.'),
('Gabe Lewis', 'bjarvis', 'fame', 'the-office', 'Shut up about the sun. SHUT UP ABOUT THE SUN!'),
('Darryl Philbin', 'bjarvis', 'fame', 'the-office', 'In a gang world, we use something called fluffy fingers. That''s when someone really gets in your face, you know you just, start ticklin'' ''em. And he starts tickling you. And pretty soon you laughing and hugging. Before you know it, you''ve forgotten the whole thing. Y''all just go to church together, and get an ice cream cone.')
ON CONFLICT DO NOTHING;