-- originally from
INSERT INTO famous_quotes (author, added_by, quote_type, quote_src, quote_tx) VALUES
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'clock speed'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'solar flares'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'electromagnetic radiation from satellite debris'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'static from nylon underwear'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'static from plastic slide rules'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'global warming'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'poor power conditioning'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'static buildup'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'doppler effect'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'hardware stress fractures'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'magnetic interference from money/credit cards'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'dry joints on cable plug'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'we''re waiting for [the phone company] to fix that line'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'sounds like a Windows problem, try calling Microsoft support'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'temporary routing anomaly'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'somebody was calculating pi on the server'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'fat electrons in the lines'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'excess surge protection'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'floating point processor overflow'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'divide-by-zero error'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'POSIX compliance problem'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'monitor resolution too high'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'improperly oriented keyboard'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'network packets travelling uphill (use a carrier pigeon)'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Decreasing electron flux'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'first Saturday after first full moon in Winter'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'radiosity depletion'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'CPU radiator broken'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'It works the way the Wang did, what''s the problem'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'positron router malfunction'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'cellular telephone interference'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'techtonic stress'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'piezo-electric interference'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', '(l)user error'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'working as designed'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'dynamic software linking table corrupted'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'heavy gravity fluctuation, move computer to floor rapidly'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'secretary plugged hairdryer into UPS'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'terrorist activities'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'not enough memory, go get system upgrade'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'interrupt configuration error'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'spaghetti cable cause packet failure'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'boss forgot system password'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'bank holiday - system operating credits  not recharged'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'virus attack, luser responsible'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'waste water tank overflowed onto computer'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Complete Transient Lockout'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'bad ether in the cables'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Bogon emissions'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Change in Earth''s rotational speed'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Cosmic ray particles crashed through the hard disk platter'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Smell from unhygienic janitorial staff wrecked the tape heads'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Little hamster in running wheel had coronary; waiting for replacement to be Fedexed from Wyoming'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Evil dogs hypnotised the night shift'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Plumber mistook routing panel for decorative wall fixture'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Electricians made popcorn in the power supply'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Groundskeepers stole the root password'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'high pressure system failure'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'failed trials, system needs redesigned'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'system has been recalled'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'not approved by the FCC'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'need to wrap system in aluminum foil to fix problem'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'not properly grounded, please bury computer'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'CPU needs recalibration'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'system needs to be rebooted'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'bit bucket overflow'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'descramble code needed from software company'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'only available on a need to know basis'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'knot in cables caused data stream to become twisted and kinked'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'nesting roaches shorted out the ether cable'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The file system is full of it'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Satan did it'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Daemons did it'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'You''re out of memory'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'There isn''t any problem'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Unoptimized hard drive'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Typo in the code'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Yes, yes, its called a design limitation'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Look, buddy:  Windows 3.1 IS A General Protection Fault.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'That''s a great computer you have there; have you considered how it would work as a BSD machine?'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Please excuse me, I have to circuit an AC line through my head to get this database working.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Yeah, yo mama dresses you funny and you need a mouse to delete files.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Support staff hung over, send aspirin and come back LATER.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Someone is standing on the ethernet cable, causing a kink in the cable'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Windows 95 undocumented "feature"'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Runt packets'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Password is too complex to decrypt'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Boss'' kid fucked up the machine'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Electromagnetic energy loss'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Budget cuts'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Mouse chewed through power cable'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Stale file handle (next time use Tupperware(tm)!)'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Feature not yet implemented'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Internet outage'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Pentium FDIV bug'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Vendor no longer supports the product'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Small animal kamikaze attack on power supplies'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The vendor put the bug there.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'SIMM crosstalk.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'IRQ dropout'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Collapsed Backbone'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Power company testing new voltage spike (creation) equipment'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'operators on strike due to broken coffee machine'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'backup tape overwritten with copy of system manager''s favourite CD'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'UPS interrupted the server''s power'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The electrician didn''t know what the yellow cable was so he yanked the ethernet out.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The keyboard isn''t plugged in'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The air conditioning water supply pipe ruptured over the machine room'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The electricity substation in the car park blew up.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The rolling stones concert down the road caused a brown out'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The salesman drove over the CPU board.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The monitor is plugged into the serial port'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Root nameservers are out of sync'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'electro-magnetic pulses from French above ground nuke testing.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'your keyboard''s space bar is generating spurious keycodes.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'the real ttys became pseudo ttys and vice-versa.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'the printer thinks its a router.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'the router thinks its a printer.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'evil hackers from Serbia.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'we just switched to FDDI.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'halon system went off and killed the operators.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'because Bill Gates is a Jehovah''s witness and so nothing can work on St. Swithin''s day.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'user to computer ratio too high.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'user to computer ration too low.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'we just switched to Sprint.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'it has Intel Inside'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Sticky bits on disk.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Power Company having EMP problems with their reactor'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The ring needs another token'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'new management'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'telnet: Unable to connect to remote host: Connection refused'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'SCSI Chain overterminated'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'It''s not plugged in.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'because of network lag due to too many people playing deathmatch'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'You put the disk in upside down.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Daemons loose in system.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'User was distributing pornography on server; system seized by FBI.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'BNC (brain not connected)'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'UBNC (user brain not connected)'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'LBNC (luser brain not connected)'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'disks spinning backwards - toggle the hemisphere jumper.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'new guy cross-connected phone lines with ac power bus.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'had to use hammer to free stuck disk drive heads.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Too few computrons available.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Flat tire on station wagon with tapes.  ("Never underestimate the bandwidth of a station wagon full of tapes hurling down the highway" Andrew S. Tannenbaum) '),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Communications satellite used by the military for star wars.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Party-bug in the Aloha protocol.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Insert coin for new game'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Dew on the telephone lines.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Arcserve crashed the server again.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Some one needed the powerstrip, so they pulled the switch plug.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'My pony-tail hit the on/off switch on the power strip.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Big to little endian conversion error'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'You can tune a file system, but you can''t tune a fish (from most tunefs man pages)'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Dumb terminal'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Zombie processes haunting the computer'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Incorrect time synchronization'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Defunct processes'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Stubborn processes'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'non-redundant fan failure '),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'monitor VLF leakage'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'bugs in the RAID'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'no "any" key on keyboard'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'root rot'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Backbone Scoliosis'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', '/pub/lunch'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'excessive collisions & not enough packet ambulances'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'le0: no carrier: transceiver cable problem?'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'broadcast packets on wrong frequency'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'popper unable to process jumbo kernel'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'NOTICE: alloc: /dev/null: filesystem full'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'pseudo-user on a pseudo-terminal'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Recursive traversal of loopback mount points'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Backbone adjustment'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'OS swapped to disk'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'vapors from evaporating sticky-note adhesives'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'sticktion'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'short leg on process table'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'multicasts on broken packets'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'ether leak'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Atilla the Hub'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'endothermal recalibration'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'filesystem not big enough for Jumbo Kernel Patch'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'loop found in loop in redundant loopback'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'system consumed all the paper for paging'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'permission denied'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Reformatting Page. Wait...'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', '..disk or the processor is on fire.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'SCSI''s too wide.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Proprietary Information.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Just type ''mv * /dev/null''.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'runaway cat on system.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Did you pay the new Support Fee?'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'We only support a 1200 bps connection.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'We only support a 28000 bps connection.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Me no internet, only janitor, me just wax floors.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'I''m sorry a pentium won''t do, you need an SGI to connect with us.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Post-it Note Sludge leaked into the monitor.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'the curls in your keyboard cord are losing electricity.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The monitor needs another box of pixels.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'RPC_PMAP_FAILURE'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'kernel panic: write-only-memory (/dev/wom0) capacity exceeded.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Write-only-memory subsystem too slow for this machine. Contact your local dealer.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Just pick up the phone and give modem connect sounds. "Well you said we should get more lines so we don''t have voice lines."'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Quantum dynamics are affecting the transistors'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Police are examining all internet packets in the search for a narco-net-trafficker'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'We are currently trying a new concept of using a live mouse.  Unfortunately, one has yet to survive being hooked up to the computer.....please bear with us.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Your mail is being routed through Germany ... and they''re censoring us.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Only people with names beginning with ''A'' are getting mail this week (a la Microsoft)'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'We didn''t pay the Internet bill and it''s been cut off.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Lightning strikes.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Of course it doesn''t work. We''ve performed a software upgrade.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Change your language to Finnish.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Fluorescent lights are generating negative ions. If turning them off doesn''t work, take them out and put tin foil on the ends.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'High nuclear activity in your area.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'What office are you in? Oh, that one.  Did you know that your building was built over the universities first nuclear research site? And wow, aren''t you the lucky one, your office is right over where the core is buried!'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The MGs ran out of gas.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The UPS doesn''t have a battery backup.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Recursivity.  Call back if it happens again.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Someone thought The Big Red Button was a light switch.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The mainframe needs to rest.  It''s getting old, you know.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'I''m not sure.  Try calling the Internet''s head office -- it''s in the book.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The lines are all busy (busied out, that is -- why let them in to begin with?).'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Jan  9 16:41:27 huber su: ''su root'' succeeded for .... on /dev/pts/1'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'It''s those computer people in X {city of world}.  They keep stuffing things up.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'A star wars satellite accidently blew up the WAN.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Fatal error right in front of screen'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'That function is not currently supported, but Bill Gates assures us it will be featured in the next upgrade.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'wrong polarity of neutron flow'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Lusers learning curve appears to be fractal'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'We had to turn off that service to comply with the CDA Bill.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Ionization from the air-conditioning'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'TCP/IP UDP alarm threshold is set too low.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Someone is broadcasting pygmy packets and the router doesn''t know how to deal with them.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The new frame relay network hasn''t bedded down the software loop transmitter yet. '),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Fanout dropping voltage too much, try cutting some of those little traces'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Plate voltage too low on demodulator tube'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'You did wha... oh _dear_....'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'CPU needs bearings repacked'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Too many little pins on CPU confusing it, bend back and forth until 10-20% are neatly removed. Do _not_ leave metal bits visible!'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', '_Rosin_ core solder? But...'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Software uses US measurements, but the OS is in metric...'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The computer fleetly, mouse and all.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Your cat tried to eat the mouse.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The Borg tried to assimilate your system. Resistance is futile.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'It must have been the lightning storm we had (yesterday) (last week) (last month)'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Due to Federal Budget problems we have been forced to cut back on the number of users able to access the system at one time. (namely none allowed....)'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Too much radiation coming from the soil.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Unfortunately we have run out of bits/bytes/whatever. Don''t worry, the next supply will be coming next week.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Program load too heavy for processor to lift.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Processes running slowly due to weak power supply'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Our ISP is having {switching,routing,SMDS,frame relay} problems'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'We''ve run out of licenses'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Interference from lunar radiation'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Standing room only on the bus.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'You need to install an RTFM interface.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'That would be because the software doesn''t work.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'That''s easy to fix, but I can''t be bothered.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Someone''s tie is caught in the printer, and if anything else gets printed, he''ll be in it too.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'We''re upgrading /dev/null'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The Usenet news is out of date'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Our POP server was kidnapped by a weasel.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'It''s stuck in the Web.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Your modem doesn''t speak English.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The mouse escaped.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'All of the packets are empty.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The UPS is on strike.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Neutrino overload on the nameserver'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Melting hard drives'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Someone has messed up the kernel pointers'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The kernel license has expired'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Netscape has crashed'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The cord jumped over and hit the power switch.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'It was OK before you touched it.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Bit rot'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'U.S. Postal Service'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Your Flux Capacitor has gone bad.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The Dilithium Crystals need to be rotated.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The static electricity routing is acting up...'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Traceroute says that there is a routing problem in the backbone.  It''s not our problem.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The co-locator cannot verify the frame-relay gateway to the ISDN server.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'High altitude condensation from U.S.A.F prototype aircraft has contaminated the primary subnet mask. Turn off your computer for 9 days to avoid damaging it.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Lawn mower blade in your fan need sharpening'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Electrons on a bender'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Telecommunications is upgrading. '),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Telecommunications is downgrading.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Telecommunications is downshifting.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Hard drive sleeping. Let it wake up on it''s own...'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Interference between the keyboard and the chair.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The CPU has shifted, and become decentralized.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Due to the CDA, we no longer have a root account.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'We ran out of dial tone and we''re and waiting for the phone company to deliver another bottle.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'You must''ve hit the wrong any key.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'PCMCIA slave driver'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The Token fell out of the ring. Call us when you find it.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The hardware bus needs a new token.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Too many interrupts'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Not enough interrupts'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The data on your hard drive is out of balance.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Digital Manipulator exceeding velocity parameters'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'appears to be a Slow/Narrow SCSI-0 Interface problem'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'microelectronic Riemannian curved-space fault in write-only file system'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'fractal radiation jamming the backbone'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'routing problems on the neural net'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'IRQ-problems with the Un-Interruptible-Power-Supply'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'CPU-angle has to be adjusted because of vibrations coming from the nearby road'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'emissions from GSM-phones'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'CD-ROM server needs recalibration'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'firewall needs cooling'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'asynchronous inode failure'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'transient bus protocol violation'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'incompatible bit-registration operators'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'your process is not ISO 9000 compliant'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'You need to upgrade your VESA local bus to a MasterCard local bus.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The recent proliferation of Nuclear Testing'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Elves on strike. (Why do they call EMAG Elf Magic)'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Internet exceeded Luser level, please wait until a luser logs off before attempting to log back on.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Your EMAIL is now being delivered by the USPS.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Your computer hasn''t been returning all the bits it gets from the Internet.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'You''ve been infected by the Telescoping Hubble virus.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Scheduled global CPU outage'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Your Pentium has a heating problem - try cooling it with ice cold water.(Do not turn off your computer, you do not want to cool down the Pentium Chip while he isn''t working, do you?)'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Your processor has processed too many instructions.  Turn it off immediately, do not type any commands!!'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Your packets were eaten by the terminator'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Your processor does not develop enough heat.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'We need a licensed electrician to replace the light bulbs in the computer room.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The POP server is out of Coke'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Fiber optics caused gas main leak'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Server depressed, needs Prozac'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'quantum decoherence'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'those damn raccoons!'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'suboptimal routing experience'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'A plumber is needed, the network drain is clogged'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', '50% of the manual is in .pdf readme files'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'the AA battery in the wallclock sends magnetic interference'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'the xy axis in the trackball is coordinated with the summer solstice'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'the butane lighter causes the pincushioning'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'old inkjet cartridges emanate barium-based fumes'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'manager in the cable duct'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'We''ll fix that in the next (upgrade, update, patch release, service pack).'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'HTTPD Error 666 : BOFH was here'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'HTTPD Error 4004 : very old Intel cpu - insufficient processing power'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The ATM board has run out of 10 pound notes.  We are having a whip round to refill it, care to contribute ?'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Network failure -  call NBC'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Having to manually track the satellite.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Your/our computer(s) had suffered a memory leak, and we are waiting for them to be topped up.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The rubber band broke'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'We''re on Token Ring, and it looks like the token got loose.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Stray Alpha Particles from memory packaging caused Hard Memory Error on Server.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'paradigm shift...without a clutch'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'PEBKAC (Problem Exists Between Keyboard And Chair)'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The cables are not the same length.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Second-system effect.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Chewing gum on /dev/sd3c'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Boredom in the Kernel.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'the daemons! the daemons! the terrible daemons!'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'I''d love to help you -- it''s just that the Boss won''t let me near the computer. '),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'struck by the Good Times virus'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'YOU HAVE AN I/O ERROR -> Incompetent Operator error'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Your parity check is overdrawn and you''re out of cache.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Communist revolutionaries taking over the server room and demanding all the computers in the building or they shoot the sysadmin. Poor misguided fools.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Plasma conduit breach'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Out of cards on drive D:'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Sand fleas eating the Internet cables'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'parallel processors running perpendicular today'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'ATM cell has no roaming feature turned on, notebooks can''t connect'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Webmasters kidnapped by evil cult.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Failure to adjust for daylight savings time.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Virus transmitted from computer to sysadmins.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Virus due to computers having unsafe sex.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Incorrectly configured static routes on the corerouters.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Forced to support NT servers; sysadmins quit.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Suspicious pointer corrupted virtual machine'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'It''s the InterNIC''s fault.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Root name servers corrupted.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Budget cuts forced us to sell all the power cords for the servers.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Someone hooked the twisted pair wires into the answering machine.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Operators killed by year 2000 bug bite.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'We''ve picked COBOL as the language of choice.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Operators killed when huge stack of backup tapes fell over.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Robotic tape changer mistook operator''s tie for a backup tape.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Someone was smoking in the computer room and set off the halon systems.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Your processor has taken a ride to Heaven''s Gate on the UFO behind Hale-Bopp''s comet.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'it''s an ID-10-T error'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Dyslexics retyping hosts file on servers'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The Internet is being scanned for viruses.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Your computer''s union contract is set to expire at midnight.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Bad user karma.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', '/dev/clue was linked to /dev/null'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Increased sunspot activity.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'We already sent around a notice about that.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'It''s union rules. There''s nothing we can do about it. Sorry.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Interference from the Van Allen Belt.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Jupiter is aligned with Mars.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Redundant ACLs. '),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Mail server hit by UniSpammer.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'T-1''s congested due to porn traffic to the news server.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Data for intranet got routed through the extranet and landed on the internet.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'We are a 100% Microsoft Shop.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'We are Microsoft.  What you are experiencing is not a problem; it is an undocumented feature.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Sales staff sold a product we don''t offer.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Secretary sent chain letter to all 5000 employees.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Sysadmin didn''t hear pager go off due to loud music from bar-room speakers.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Sysadmin accidentally destroyed pager with a large hammer.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Sysadmins unavailable because they are in a meeting talking about why they are unavailable so much.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Bad cafeteria food landed all the sysadmins in the hospital.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Route flapping at the NAP.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Computers under water due to SYN flooding.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The vulcan-death-grip ping has been applied.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Electrical conduits in machine room are melting.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Traffic jam on the Information Superhighway.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Radial Telemetry Infiltration'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Cow-tippers tipped a cow onto the server.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'tachyon emissions overloading the system'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Maintenance window broken'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'We''re out of slots on the server'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Computer room being moved.  Our systems are down for the weekend.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Sysadmins busy fighting SPAM.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Repeated reboots of the system failed to solve problem'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Feature was not beta tested'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Domain controller not responding'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Someone else stole your IP address, call the Internet detectives!'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'It''s not RFC-822 compliant.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'operation failed because: there is no message for this error (#1014)'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'stop bit received'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'internet is needed to catch the etherbunny'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'network down, IP packets delivered via UPS'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Firmware update in the coffee machine'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Temporal anomaly'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Mouse has out-of-cheese-error'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Borg implants are failing'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Borg nanites have infested the server'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'error: one bad user found in front of screen'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Please state the nature of the technical emergency'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Internet shut down due to maintenance'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Daemon escaped from pentagram'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'crop circles in the corn shell'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'sticky bit has come loose'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Hot Java has gone cold'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Cache miss - please take better aim next time'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Hash table has woodworm'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Trojan horse ran out of hay'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Zombie processes detected, machine is haunted.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'overflow error in /dev/null'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Browser''s cookie is corrupted -- someone''s been nibbling on it.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Mailer-daemon is busy burning your message in hell.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'According to Microsoft, it''s by design'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'vi needs to be upgraded to vii'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'greenpeace free''d the mallocs'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Terrorists crashed an airplane into the server room, have to remove /bin/laden. (rm -rf /bin/laden)'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'astropneumatic oscillations in the water-cooling'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Somebody ran the operating system through a spelling checker.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Rhythmic variations in the voltage reaching the power supply.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Keyboard Actuator Failure.  Order and Replace.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Packet held up at customs.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Propagation delay.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'High line impedance.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Someone set us up the bomb.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Power surges on the Underground.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Don''t worry; it''s been deprecated. The new one is worse.'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Excess condensation in cloud network'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'It is a layer 8 problem'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'The math co-processor had an overflow error that leaked out and shorted the RAM'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Leap second overloaded RHEL6 servers'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'DNS server drank too much and had a hiccup'),
('The Bastard Operator From Hell', 'bjarvis', 'nerd-excuse', 'bofh', 'Your machine had the fuses in backwards.')
ON CONFLICT DO NOTHING;